INSERT INTO LOCATION (city,state,country,zipcode,address) VALUES ('Berlin','Eastern Germany','Germany',10115,'Mollstraße 4, 10178, Berlin, Germany');
INSERT INTO LOCATION (city,state,country,zipcode,address) VALUES ('Munic',' Northen Germany','Germany',20815,'34 street');
INSERT INTO LOCATION (city,state,country,zipcode,address) VALUES ('vienna','Burgenland','Austria',30895,'45 street');
INSERT INTO LOCATION (city,state,country,zipcode,address) VALUES ('Delhi','New Delhi','India',20802,'Malviya nagar');
INSERT INTO LOCATION (city,state,country,zipcode,address) VALUES ('Bangalore','Karnatak','India',19053,'Manyata tech Park');
INSERT INTO LOCATION (city,state,country,zipcode,address) VALUES ('Pune','Maharashtra','India',208020,'Hinze wadi');
INSERT INTO BOOKING_DEF (name,rating,category,image,reputation,badge,price,availability,location_id) VALUES ('La-Maridin',5,'Hotel', 'image-url.com',500,'YELLOW',5000,4,1);
INSERT INTO BOOKING_DEF (name,rating,category,image,reputation,badge,price,availability,location_id) VALUES ('Radisson Blue',5,'Hotel', 'image-url.com',700,'GREEN',6000,40,2);
INSERT INTO BOOKING_DEF (name,rating,category,image,reputation,badge,price,availability,location_id) VALUES ('Four Points By Sharitton',4,'Hotel', 'image-url.com',400,'YELLOW',5000,24,3);
INSERT INTO BOOKING_DEF (name,rating,category,image,reputation,badge,price,availability,location_id) VALUES ('ITC Maurya Delhi',3,'Hotel', 'image-url.com',400,'RED',5000,2,4);
INSERT INTO BOOKING_DEF (name,rating,category,image,reputation,badge,price,availability,location_id) VALUES ('Holiday Inn',4,'Hotel', 'image-url.com',400,'YELLOW',2000,14,5);
